---
kind: pipeline
type: docker
name: default

steps:
- name: Launch Prebuild Script
  image: ubuntu
  commands:
  - apt update && apt install git python3 -y
  - python3 tools/prebuild.py $(git rev-parse --short HEAD) devel

- name: Build ModularKit
  image: ubuntu
  commands:
  - apt update && apt install openjdk-8-jdk make -y
  - make clean build-nightly

trigger:
  branch:
  - main