---
kind: pipeline
type: docker
name: default

steps:
- name: Build ModularKit
  image: ubuntu
  commands:
  - apt update && apt install git openjdk-8-jdk make -y
  - make clean build-nightly

trigger:
  branch:
  - main