name: Nightly Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Set up Python 3.9
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install Python dependencies
        run: python -m pip install PyGithub
        
      - name: Launch Pre-Build Nightly Prep Script
        shell: bash
        env:
          GTOKEN: ${{ secrets.TOKEN }}
        run: python Tools/Github_Workflows-Scripts/prebuild-nightly.py ${GTOKEN}
        
      - name: Prepare Build ModularKit
        uses: actions/setup-java@v2
        with:
          java-version: '8.0'
          distribution: 'adopt'
      - name: Build ModularKit
        run: mvn -f nightly-pom.xml --batch-mode clean install
